import numpy as np

from evorob.world.robot.controllers.base import Controller


class NeuralNetworkController(Controller):
    def __init__(
        self,
        input_size: int,
        output_size: int,
        hidden_size: int = 16,
    ):
        # Here we randomly initialize our neural network layers, 
        # as well as our input and output size.
        self.n_input = input_size
        self.n_output = output_size
        self.n_hidden = hidden_size
        
        self.input_to_hidden = ... # TODO!
        self.hidden_to_output = ... # TODO!

        self.n_params_i2h = ... # TODO!
        self.n_params_h2o = ... # TODO!

        self.n_params = self.get_num_params()
        

    def get_action(self, state):
        # We perform a forward pass computation through the layers,
        # providing an action.
        # TODO!
        raise NotImplementedError

    def set_weights(self, encoding):
        # We take the weights generated by the evolutionary algorithm,
        # and overwrite the parameters of the neural network with the
        # evolved parameters.
        # TODO!
        raise NotImplementedError

    def geno2pheno(self, genotype):
        """Alias for set_weights (genotype to phenotype mapping)."""
        self.set_weights(genotype)

    def get_num_params(self):
        # To provide a genetic encoding for our neural network controller,
        # we compute and store the number of parameters in our NN class.
        # TODO!
        raise NotImplementedError
    
    def reset_controller(self, batch_size=1) -> None:
        pass